[build]
    functions = "functions"
[[redirects]]
    from = "https://stanyukika.com"
    to = "/.netlify/functions/random"
    status = 301
[[redirects]]
    from = "http://stanyukika.com"
    to = "/.netlify/functions/random"
    status = 301
[[redirects]]
    from = "/*"
    to = "/.netlify/functions/random"
    status = 301